### ISSUE TITLE
Improve community health

### ISSUE THREAD

**Issue by brucellino** [EGI-Federation/glite-info-update-endpoints#5]
There is no material to encourage community participation. We need to add all of it

  - [x] license
  - [x] Contribution guide
  - [x] README
  - [x] issue template
  - [x] pull request template
  - [x] Code of Conduct.

**Comment by gwarf** [comment]
License and README were added in #8.
As this repo will probably be merged with another component it may be enough for the time being.

**Comment by gwarf** [comment]
https://github.com/EGI-Foundation/nagios-plugins-bdii provides files that can be used to implement this.

**Comment by gwarf** [comment]
all done.
